pipeline {
	agent any 
	
	stages{
		stage('Compile stage') {
			steps {
				withMaven(maven: 'maven_3_6_0') {
					sh 'mvn -f cisco-hr/pom.xml package'
				}
			}
		}
		
		stage('Test stage') {
			steps {
				echo "Running test scripts"
			}
		}
		
		stage('Deploy stage') {
			steps {
				echo "Deploying..."
			}
		}
	}
}
