node {
	stage('SCM checkout') {
		git 'https://github.com/JosephPravin/hr-maven'
	}
	
	stage('Compile-Package') {
		def mvnHome =  tool name: 'maven_3_6_0', type: 'maven'   
      		sh "${mvnHome}/bin/mvn -f cisco-hr/pom.xml package"
	}
	
	stage('Stop Tomcat'){
		sh  'ssh -o StrictHostKeyChecking=no jpravinp@10.98.12.238 /Users/jpravinp/Desktop/tomcat/bin/shutdown.sh'
   	}
	
	stage('Copy jar to webapps') {
		sh 'scp -o StrictHostKeyChecking=no cisco-hr/target/*.jar jpravinp@10.98.12.238:/Users/jpravinp/Desktop/tomcat/webapps'
	}
	
	stage('Start tomcat') {
		sh  'ssh -o StrictHostKeyChecking=no jpravinp@10.98.12.238 /Users/jpravinp/Desktop/tomcat/bin/startup.sh'
	}
}

/*
pipeline {
	agent any 
	
	stages{
		
		stage('Deploy to tomcat') {
			steps{
				sh  'ssh -o StrictHostKeyChecking=no jpravinp@10.98.12.238 /Users/jpravinp/Desktop/tomcat/bin/shutdown.sh'
				sh 'scp -o StrictHostKeyChecking=no cisco-hr/target/*.jar jpravinp@10.98.12.238:/Users/jpravinp/Desktop/tomcat/webapps'
				sh  'ssh -o StrictHostKeyChecking=no jpravinp@10.98.12.238 /Users/jpravinp/Desktop/tomcat/bin/startup.sh'
				/*sshagent(['jpravinp']) {
				sh 'scp -o StrictHostKeyChecking=no cisco-hr/target/*.jar jpravinp@10.98.12.68:/Users/jpravinp/Desktop/tomcat/webapps'
			}*/
			}
			
		}
	}
}
*/

